#define THERMAL_BOXLINE_HOR_LIGHT 0
#define THERMAL_BOXLINE_HOR_DARK 1
#define THERMAL_BOXLINE_HOR_LIGHT3DOT 2
#define THERMAL_BOXLINE_HOR_DARK3DOT 3
#define THERMAL_BOXLINE_HOR_LIGHT4DOT 4
#define THERMAL_BOXLINE_HOR_DARK4DOT 5
#define THERMAL_BOXLINE_HOR_DOUBLLINE 6
#define THERMAL_BOXLINE_HOR_LIGHT2DOT 7
#define THERMAL_BOXLINE_HOR_DARK2DOT 8
#define THERMAL_BOXLINE_HOR_LIGHTLEFT 9
#define THERMAL_BOXLINE_HOR_LIGHTRIGHT 10
#define THERMAL_BOXLINE_HOR_DARKLEFT 11
#define THERMAL_BOXLINE_HOR_DARKRIGHT 12
#define THERMAL_BOXLINE_HOR_TEARRIGHT 13
#define THERMAL_BOXLINE_HOR_TEARLEFT 14

#define THERMAL_BOXLINE_VER_LIGHT 0
#define THERMAL_BOXLINE_VER_DARK 1
#define THERMAL_BOXLINE_VER_LIGHT3DOT 2
#define THERMAL_BOXLINE_VER_DARK3DOT 3
#define THERMAL_BOXLINE_VER_LIGHT4DOT 4
#define THERMAL_BOXLINE_VER_DARK4DOT 5
#define THERMAL_BOXLINE_VER_LIGHT2DOT 6
#define THERMAL_BOXLINE_VER_DARK2DOT 7
#define THERMAL_BOXLINE_VER_DOUBLELINE 8
#define THERMAL_BOXLINE_VER_LIGHTTOP 9
#define THERMAL_BOXLINE_VER_LIGHTBOTTOM 10
#define THERMAL_BOXLINE_VER_DARKTOP 11
#define THERMAL_BOXLINE_VER_DARK_BOTTOM 12
#define THERMAL_BOXLINE_VER_TEARDOWN 13
#define THERMAL_BOXLINE_VER_TEARUP 14

#define THERMAL_BOXLINE_CORNER_TL_LIGHT 0
#define THERMAL_BOXLINE_CORNER_TL_LVERDHOR 1
#define THERMAL_BOXLINE_CORNER_TL_DVERLHOR 2
#define THERMAL_BOXLINE_CORNER_TL_DARK 3
#define THERMAL_BOXLINE_CORNER_TR_LIGHT 4
#define THERMAL_BOXLINE_CORNER_TR_LVERDHOR 5
#define THERMAL_BOXLINE_CORNER_TR_DVERLHOR 6
#define THERMAL_BOXLINE_CORNER_TR_DARK 7
#define THERMAL_BOXLINE_CORNER_BL_LIGHT 8
#define THERMAL_BOXLINE_CORNER_BL_LVERDHOR 9
#define THERMAL_BOXLINE_CORNER_BL_DVERLHOR 10
#define THERMAL_BOXLINE_CORNER_BL_DARK 11
#define THERMAL_BOXLINE_CORNER_BR_LIGHT 12
#define THERMAL_BOXLINE_CORNER_BR_LVERDHOR 13
#define THERMAL_BOXLINE_CORNER_BR_DVERLHOR 14
#define THERMAL_BOXLINE_CORNER_BR_DARK 15
#define THERMAL_BOXLINE_CORNER_TL_1VER2HOR 16
#define THERMAL_BOXLINE_CORNER_TL_2VER1HOR 17
#define THERMAL_BOXLINE_CORNER_TL_DOUBLE 18
#define THERMAL_BOXLINE_CORNER_TR_1VER_2HOR 19
#define THERMAL_BOXLINE_CORNER_TR_2VER1HOR 20
#define THERMAL_BOXLINE_CORNER_TR_DOUBLE 21
#define THERMAL_BOXLINE_CORNER_BL_1VER2HOR 22
#define THERMAL_BOXLINE_CORNER_BL_2VER1HOR 23
#define THERMAL_BOXLINE_CORNER_BL_DOUBLE 24
#define THERMAL_BOXLINE_CORNER_BR_1VER2HOR 25
#define THERMAL_BOXLINE_CORNER_BR_2VER1HOR 26
#define THERMAL_BOXLINE_CORNER_BR_DOUBLE 27
#define THERMAL_BOXLINE_CORNER_TL_ROUND 28
#define THERMAL_BOXLINE_CORNER_TR_ROUND 29
#define THERMAL_BOXLINE_CORNER_BR_ROUND 30
#define THERMAL_BOXLINE_CORNER_BL_ROUND 31


class ThermalBox{
	private:

	public:
		ThermalBox(){

		}

		~ThermalBox(){

		}
		const wchar_t *horizontalLine(int style){
			switch(style){
				case THERMAL_BOXLINE_HOR_DARK:
					return L"━";
				case THERMAL_BOXLINE_HOR_LIGHT3DOT:
					return L"┄";
				case THERMAL_BOXLINE_HOR_DARK3DOT:
					return L"┅";
				case THERMAL_BOXLINE_HOR_LIGHT4DOT:
					return L"┈";
				case THERMAL_BOXLINE_HOR_DARK4DOT:
					return L"┉";
				case THERMAL_BOXLINE_HOR_DOUBLLINE:
					return L"═";
				case THERMAL_BOXLINE_HOR_LIGHT2DOT:
					return L"╌";
				case THERMAL_BOXLINE_HOR_DARK2DOT:
					return L"╍";
				case THERMAL_BOXLINE_HOR_LIGHTLEFT:
					return L"╴";
				case THERMAL_BOXLINE_HOR_LIGHTRIGHT:
					return L"╶";
				case THERMAL_BOXLINE_HOR_DARKLEFT:
					return L"╸";
				case THERMAL_BOXLINE_HOR_DARKRIGHT:
					return L"╺";
				case THERMAL_BOXLINE_HOR_TEARRIGHT:
					return L"╼";
				case THERMAL_BOXLINE_HOR_TEARLEFT:
					return L"╾";
				default: // THERMAL_BOXLINE_HOR_LIGHT
					return L"─";
			}
		}

		const wchar_t *verticalLine(int style){
			switch(style){
				case THERMAL_BOXLINE_VER_DARK:
					return L"┃";
				case THERMAL_BOXLINE_VER_LIGHT3DOT:
					return L"┆";
				case THERMAL_BOXLINE_VER_DARK3DOT:
					return L"┇";
				case THERMAL_BOXLINE_VER_LIGHT4DOT:
					return L"┊";
				case THERMAL_BOXLINE_VER_DARK4DOT:
					return L"┋";
				case THERMAL_BOXLINE_VER_LIGHT2DOT:
					return L"╎";
				case THERMAL_BOXLINE_VER_DARK2DOT:
					return L"╏";
				case THERMAL_BOXLINE_VER_DOUBLELINE:
					return L"║";
				case THERMAL_BOXLINE_VER_LIGHTTOP:
					return L"╵";
				case THERMAL_BOXLINE_VER_LIGHTBOTTOM:
					return L"╷";
				case THERMAL_BOXLINE_VER_DARKTOP:
					return L"╹";
				case THERMAL_BOXLINE_VER_DARK_BOTTOM:
					return L"╻";
				case THERMAL_BOXLINE_VER_TEARDOWN:
					return L"╽";
				case THERMAL_BOXLINE_VER_TEARUP:
					return L"╿";
				default: // THERMAL_BOXLINE_VER_LIGHT
					return L"│";
			}
		}

		const wchar_t *cornerLine(int style){
			switch(style){
				case THERMAL_BOXLINE_CORNER_TL_LVERDHOR:
					return L"┍";
				case THERMAL_BOXLINE_CORNER_TL_DVERLHOR:
					return L"┎";
				case THERMAL_BOXLINE_CORNER_TL_DARK:
					return L"┏";
				case THERMAL_BOXLINE_CORNER_TR_LIGHT:
					return L"┐";
				case THERMAL_BOXLINE_CORNER_TR_LVERDHOR:
					return L"┑";
				case THERMAL_BOXLINE_CORNER_TR_DVERLHOR:
					return L"┒";
				case THERMAL_BOXLINE_CORNER_TR_DARK:
					return L"┓";
				case THERMAL_BOXLINE_CORNER_BL_LIGHT:
					return L"└";
				case THERMAL_BOXLINE_CORNER_BL_LVERDHOR:
					return L"┕";
				case THERMAL_BOXLINE_CORNER_BL_DVERLHOR:
					return L"┖";
				case THERMAL_BOXLINE_CORNER_BL_DARK:
					return L"┗";
				case THERMAL_BOXLINE_CORNER_BR_LIGHT:
					return L"┘";
				case THERMAL_BOXLINE_CORNER_BR_LVERDHOR:
					return L"┙";
				case THERMAL_BOXLINE_CORNER_BR_DVERLHOR:
					return L"┚";
				case THERMAL_BOXLINE_CORNER_BR_DARK:
					return L"┛";
				case THERMAL_BOXLINE_CORNER_TL_1VER2HOR:
					return L"╒";
				case THERMAL_BOXLINE_CORNER_TL_2VER1HOR:
					return L"╓";
				case THERMAL_BOXLINE_CORNER_TL_DOUBLE:
					return L"╔";
				case THERMAL_BOXLINE_CORNER_TR_1VER_2HOR:
					return L"╕";
				case THERMAL_BOXLINE_CORNER_TR_2VER1HOR:
					return L"╖";
				case THERMAL_BOXLINE_CORNER_TR_DOUBLE:
					return L"╗";
				case THERMAL_BOXLINE_CORNER_BL_1VER2HOR:
					return L"╘";
				case THERMAL_BOXLINE_CORNER_BL_2VER1HOR:
					return L"╙";
				case THERMAL_BOXLINE_CORNER_BL_DOUBLE:
					return L"╚";
				case THERMAL_BOXLINE_CORNER_BR_1VER2HOR:
					return L"╛";
				case THERMAL_BOXLINE_CORNER_BR_2VER1HOR:
					return L"╜";
				case THERMAL_BOXLINE_CORNER_BR_DOUBLE:
					return L"╝";
				case THERMAL_BOXLINE_CORNER_TL_ROUND:
					return L"╭";
				case THERMAL_BOXLINE_CORNER_TR_ROUND:
					return L"╮";
				case THERMAL_BOXLINE_CORNER_BR_ROUND:
					return L"╯";
				case THERMAL_BOXLINE_CORNER_BL_ROUND:
					return L"╰";
				default: // THERMAL_BOXLINE_CORNER_TL_LIGHT
					return L"┌";
			}
		}

};
